ethical_eating/ethical_eating/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('users/', include('users.urls')),
    path('', include('resources.urls')),
]

ethical_eating/forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path('forum/', views.forum, name='forum'),
    path('forum/all/', views.forum_all, name='all'),
    path('forum/get_comment/<int:pk>', views.get_comment, name='get_comment'),
]

ethical_eating/forum/models.py
from django.db import models


# Create your models here.

class Thread(models.Model):
    text = models.CharField(max_length=150)
    creator = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.text}'


class Comment(models.Model):
    text = models.CharField(max_length=250)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    creator = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.text}'

ethical_eating/forum/forms.py
from django import forms


class ThreadForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control w-100'
    }))
    subject = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control w-100'
    }))


class CommentForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control w-50'
    }))
    comment = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control w-50'
    }))

ethical_eating/forum/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

from forum.forms import ThreadForm, CommentForm
from forum.models import Thread, Comment

from django.shortcuts import render, redirect


# Create your views here.


def forum(request):
    last_five = Thread.objects.all().order_by('-id')[:5]
    if request.method == 'POST':

        form = ThreadForm(request.POST)
        if form.is_valid():
            creator = form.cleaned_data['name']
            text = form.cleaned_data['subject']
            Thread(text=text, creator=creator).save()
            messages.success(request, 'Thanks for getting involved, dude')
            return redirect(reverse('forum:forum'))
    else:
        form = ThreadForm()
        cform = CommentForm()
    return render(request, 'forum/forum.html', {'last_five': last_five, 'form': form, 'cform': cform})


def forum_all(request):
    threads = Thread.objects.all()
    cform = CommentForm()
    return render(request, 'forum/forum_all.html', {'threads': threads, 'cform': cform})


def get_comment(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            creator = form.cleaned_data['name']
            text = form.cleaned_data['comment']
            thread = Thread.objects.get(pk=pk)
            Comment(text=text, thread=thread, creator=creator).save()
            messages.success(request, 'Thanks for commenting, dude')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

ethical_eating/templates/forum/forum.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
     body {
        background-image: linear-gradient(rgba(170, 170, 170, 0.8), rgba(170, 170, 170, 0.8)), url("{% static 'resources/avocado.jpg' %}");
        background-color: #abebc6;
     }
     #meter:hover .gauge-c {
        transform:rotate(.25turn);
     }
</style>
{% endblock %}


{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<!--<div id="meter" class="container" style="margin-top: 110px;">-->
<!--  <div class="gauge-a"></div>-->
<!--  <div class="gauge-b"></div>-->
<!--  <div class="gauge-c"></div>-->
<!--  <div class="gauge-data">-->
<!--    <h5 style="margin-top: 50px;" id="percent">hover for<br> your ethical level</h5>-->
<!--  </div>-->
<!--</div>-->
<center><h1 class="nice-font space ledge title">Forum</h1></center>
<div class="container space">
    <div class="row">
        <div class="col-md-8">
            {% for thread in last_five %}
            <div style="margin-bottom: 40px;" class="card">
              <div class="card-header">
                Created by: {{ thread.creator }}
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ thread.text }}</h5>
                  <form action="{% url 'forum:get_comment' thread.id %}" method="post">
                      {% csrf_token %}
                    {{ cform.as_p }}
                    <button type="submit" class="btn btn-secondary" >Submit</button>
                  </form><br>
                  <h4>Comments:</h4>
                  {% for comment in thread.comment_set.all %}
                  <p class="card-text">{{ comment.creator }}: {{ comment }}</p>
                  {% endfor %}
              </div>
            </div>
            {% endfor %}
            <a href="{% url 'forum:all' %}"  style="margin-top: 25px; margin-bottom: 45px; width: 200px" class="btn btn-secondary">See More</a>
        </div>
        <div class="card-mx-auto col-md-4">
            <h2 class="ledge nice-font">Create a thread:</h2>
            <div class="card-body">
                <form action="{% url 'forum:forum' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary" >Submit</button>
                </form>
            </div>
            <a href="{% url 'forum:all' %}"  style="margin-top: 25px; width: 200px" class="btn btn-secondary">See All</a>
        </div>
    </div>
</div>
{% endblock %}

ethical_eating/templates/forum/forum_all.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
     body {
        background-image: linear-gradient(rgba(170, 170, 170, 0.8), rgba(170, 170, 170, 0.8)), url("{% static 'resources/avocado.jpg' %}");
        background-color: #abebc6;
     }
</style>
{% endblock %}


{% block content %}
<div class="container space">
    <div class="row">
        <div class="col">
            {% for thread in threads %}
            <div style="margin-bottom: 40px;" class="card">
              <div class="card-header">
                Created by: {{ thread.creator }}
              </div>
              <div class="card-body">
                <h5 class="card-title">{{ thread.text }}</h5>
                  <form action="{% url 'forum:get_comment' thread.id %}" method="post">
                      {% csrf_token %}
                    {{ cform.as_p }}
                    <button type="submit" class="btn btn-secondary" >Submit</button>
                  </form><br>
                  <h4>Comments:</h4>
                  {% for comment in thread.comment_set.all %}
                <p class="card-text">{{ comment.creator }}: {{ comment }}</p>
                  {% endfor %}
              </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}