ethical_eating/ethical_eating/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('users/', include('users.urls')),
    path('', include('resources.urls')),
]

ethical_eating/forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path('forum/', views.forum, name='forum'),
    path('forum/all/', views.forum_all, name='all'),
    path('forum/get_comment/<int:pk>', views.get_comment, name='get_comment'),
]

ethical_eating/resources/urls.py
from django.urls import path

from resources import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'resources'

urlpatterns = [
    path('', views.index, name='index'),
    path('why', views.why, name='why'),
    path('questions/', views.questions, name='questions'),
    path('resources/', views.resources, name='resources'),
    path('resources/books/', views.books, name='books'),
    path('resources/food/', views.food, name='food'),
    path('resources/food/reviews/<int:pk>', views.reviews, name='reviews'),
    path('resources/products/', views.products, name='products'),
    path('resources/sources/bible', views.bible, name='bible'),
    path('resources/sources/talmud', views.talmud, name='talmud'),
    path('resources/sources/rabbis', views.rabbis, name='rabbis'),
    path('resources/sources/thinkers', views.thinkers, name='thinkers'),
    path('about/', views.about, name='about'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ethical_eating/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('trump/', views.trump, name='trump'),
]

ethical_eating/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jewish Ethical Eating</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dosis|Girassol|Nunito+Sans&display=swap" rel="stylesheet">
    <style>
        .nice-font, label {
            font-family: 'Dosis', sans-serif;
        }
        label {
            font-size: 25px;
        }
        .bible-font {
            font-family: 'Girassol', cursive;
        }
        .quiz-font {
            font-family: 'Nunito Sans', sans-serif;
        }
        .title {
            font-size: 50px;
        }
        .card {
            background-color: rgba(245, 245, 245, 0.7);
        }
        .card-header, .card-footer {
            opacity: 1;
        }
        .space {
            margin-top: 90px;
        }
        .gray {
            color: rgba(255,255,255,.5);
        }

        #meter {
          width: 420px;
          height: 200px;
          position: static;
          top: 30%;
          left: 50%;
          overflow: hidden;
          text-align: center;
          transform: translate(-50%, -50%);
          margin-left: 910px;
        }

        .gauge-a {
          z-index: 1;
          position: absolute;
          background-color: rgba(255,255,255,.2);
          width: 400px;
          height: 200px;
          top: 0%;
          border-radius: 250px 250px 0px 0px;
        }

        .gauge-b {
          z-index: 3;
          position: absolute;
          background-color: #222;
          width: 250px;
          height: 125px;
          top: 75px;
          margin-left: 75px;
          margin-right: auto;
          border-radius: 250px 250px 0px 0px;
        }

        .gauge-c {
          z-index: 2;
          position: absolute;
          background-color: #5664F9;
          width: 400px;
          height: 200px;
          top: 200px;
          margin-left: auto;
          margin-right: auto;
          border-radius: 0px 0px 200px 200px;
          transform-origin: center top;
          transition: all 1.3s ease-in-out;
        }
        #meter:hover .gauge-data { color: rgba(255,255,255,1); }

        .gauge-data {
          z-index: 4;
          color: rgba(255,255,255,.2);
          font-size: 1.5em;
          line-height: 25px;
          position: absolute;
          width: 400px;
          height: 200px;
          top: 90px;
          margin-left: auto;
          margin-right: auto;
          transition: all 1s ease-out;
        }
</style>
    {% block css %}
    {% endblock %}

</head>
<body>
    {% block navbar %}
    {% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'resources:why' %}">
            <img src="{% static 'resources/kosher_vegan.png' %}" width="55" height="30" alt="symbols">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'resources:index' %}">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'resources:questions' %}">FAQs</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Resources
                    </a>
                    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item gray" href="{% url 'resources:books' %}">Books</a>
                        <a class="dropdown-item gray" href="{% url 'resources:resources' %}#sources">Sources</a>
                        <a class="dropdown-item gray" href="{% url 'resources:food' %}">Restaurants</a>
                        <a class="dropdown-item gray" href="{% url 'resources:products' %}">Products</a>
                    <div class="dropdown-divider gray"></div>
                        <a class="dropdown-item gray" href="{% url 'resources:resources' %}">All</a>
                    </div>
                </li>
                <a class="nav-item nav-link" href="{% url 'forum:forum' %}">Forum</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        About
                    </a>
                    <div class="dropdown-menu bg-dark " aria-labelledby="navbarDropdown">
                        <a class="dropdown-item gray" href="{% url 'resources:about' %}#what">What is it</a>
                        <a class="dropdown-item gray" href="{% url 'resources:about' %}#why">Why is it important</a>
                        <a class="dropdown-item gray" href="{% url 'resources:about' %}#how">How to get involved</a>
                    <div class="dropdown-divider gray"></div>
                        <a class="dropdown-item gray" href="{% url 'resources:about' %}">Main</a>
                    </div>
                </li>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout ({{ user.username }})</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    <footer>
        <div class="footer-copyright text-center py-3 fixed-bottom text-light">© 2020 Copyright:
            <a href="https://github.com/elibrand">JEE</a>
        </div>
     </footer>
    {% endblock %}

    {% block js %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>