ethical_eating/ethical_eating/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('users/', include('users.urls')),
    path('', include('resources.urls')),
]

ethical_eating/forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path('forum/', views.forum, name='forum'),
    path('forum/all/', views.forum_all, name='all'),
    path('forum/get_comment/<int:pk>', views.get_comment, name='get_comment'),
]

ethical_eating/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('trump/', views.trump, name='trump'),
]

ethical_eating/users/models.py
from django.db import models

# Create your models here.

ethical_eating/users/forms.py
from django.forms import Form, CharField, TextInput, PasswordInput, EmailInput, Select, ChoiceField, IntegerField


class RegisterForm(Form):
    username = CharField(widget=TextInput(attrs={
        'class': 'form-control w-50'
    }))
    password = CharField(widget=PasswordInput(attrs={
        'class': 'form-control w-50'
    }))
    email = CharField(label='Email', widget=EmailInput(attrs={
        'class': 'form-control w-50'
    }))
    first_name = CharField(label='First Name', widget=TextInput(attrs={
        'class': 'form-control w-50'
    }))
    last_name = CharField(label='Last Name', widget=TextInput(attrs={
        'class': 'form-control w-50'
    }))


class LoginForm(Form):
    username = CharField(widget=TextInput(attrs={
        'class': 'form-control w-50'
    }))
    password = CharField(widget=PasswordInput(attrs={
        'class': 'form-control w-50'
    }))


class BMIForm(Form):
    FEET_CHOICES = list(zip(map(str, range(1, 9)), list(range(1, 9))))
    INCH_CHOICES = list(zip(map(str, range(0, 13)), list(range(0, 13))))
    feet = IntegerField(widget=Select(choices=FEET_CHOICES, attrs={
        'class': 'form-control w-50'
    }))
    inches = IntegerField(widget=Select(choices=INCH_CHOICES, attrs={
        'class': 'form-control w-50'
    }))
    weight = IntegerField(label='Weight in Pounds:', widget=TextInput(attrs={
        'class': 'form-control w-50'
    }))


def cal_height(feet, inches):
    """
    converts height in feet and inches into inches
    :return: height in inches
    """
    return (feet * 12) + inches


def cal_bmi(height, weight):
    """
    calculates bmi then rounds it to integer with one decimal point
    :param height: user's height in meters
    :param weight: user's weight in kg
    :return: bmi with one decimal
    """
    return round(weight / (height ** 2), 1)

ethical_eating/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from users.forms import RegisterForm, LoginForm, BMIForm, cal_height, cal_bmi


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                messages.warning(request, f"{form.cleaned_data['username']} is already in use")
                return redirect(reverse('users:login'))
            user = User.objects.create_user(**form.cleaned_data)
            messages.info(request, f'{user.username} successfully created!')
            return redirect(reverse('users:login'))
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, **form.cleaned_data)
            if user:
                login(request, user)
                messages.info(request, 'Successfully logged in!')
                return redirect(reverse('users:profile'))
            else:
                messages.error(request, 'Bad authentication.....')
                return redirect(reverse('users:login'))

    else:
        form = LoginForm()

    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.info(request, 'Logged out')
    return redirect(reverse('users:login'))


@login_required
def profile(request):
    bmi = ''
    if request.method == 'POST':
        form = BMIForm(request.POST)
        if form.is_valid():
            feet = form.cleaned_data['feet']
            print(f'feet:{feet}')
            inches = form.cleaned_data['inches']
            print(f'inches:{inches}')
            inch_height = cal_height(feet, inches)
            weight = form.cleaned_data['weight']

            meter_height = cal_height(feet, inches) * 0.0254
            print(f'meter_height:{meter_height}')
            kg_weight = form.cleaned_data['weight'] * 0.453592
            print(f'kg_weight:{kg_weight}')

            bmi = cal_bmi(meter_height, kg_weight)

            messages.success(request, f'Your BMI is {bmi}')
        else:
            messages.error(request, 'Check your info and try again')

    else:
        form = BMIForm()
    return render(request, 'users/profile.html', {'form': form})


def trump(request):
    return render(request, 'users/trump.html')

ethical_eating/templates/users/login.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-image: linear-gradient(rgba(170, 170, 170, 0.8), rgba(170, 170, 170, 0.8)), url("{% static 'resources/avocado.jpg' %}");
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<center>
    <h1 class="nice-font space title">Login</h1>
    <div class="card space" style="width: 25rem;">
      <img src="{% static 'users/kosher_vegan.png' %}" class="card-img-top" style="width: 50%; margin: auto; margin-top: 30px;" alt="...">
      <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary" >Login</button>
          </form>
      </div>
    </div>

</center>
{% endblock %}

ethical_eating/templates/users/profile.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-image: linear-gradient(rgba(170, 170, 170, 0.8), rgba(170, 170, 170, 0.8)), url("{% static 'resources/avocado.jpg' %}");
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<center><h1 class="nice-font space title">My Profile ({{ user.username }})</h1></center>

<div class="container">
    <div class="row space">
         <div class="col-md-8">
            <div class="list-group">
              <a href="#" class="list-group-item list-group-item-action active">
                Awesome content just for holy vegans
              </a>
              <a href="http://www.sentientdevelopments.com/2007/08/meat-eaters-are-bad-people.html" class="list-group-item list-group-item-action">Meat Eaters Are Bad People</a>
              <a href="https://thoughtcatalog.com/thien-tang/2015/05/10-reasons-why-vegans-are-evil/" class="list-group-item list-group-item-action">10 Reasons Why Vegans Are Evil</a>
              <a href="{% url 'users:trump' %}" class="list-group-item list-group-item-action">What Meat-Eaters Look Like</a>
            </div>
        </div>
        <div class="col-md-4" style="margin-bottom: 90px;">
            <div class="card" style="width: 30rem">
                <div class="card-header">
                    My Info
                </div>
                <div class="card-body">
                    username: {{ user.username }}<br>
                    name: {{ user.first_name }} {{ user.last_name }} <br>
                    email: {{ user.email }}<br>
                </div>
            </div>
            <div class="card-body">
                <h3 class="nice-font">BMI Calculator</h3>
                <button type="button" class="btn btn-secondary" onclick="appear()">Imperial</button>
                <button type="button" class="btn btn-secondary">Metric</button>
                <form id ="imperial" method="post">
                {% csrf_token %}
                    <h4 class="nice-font">Height:</h4>

                {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary">Calculate</button>
                </form>
            </div>
            <img style="height: 270px; width: 480px;" src="{% static 'users/bmi_chart.jpeg' %}" alt="chart">
        </div>
    </div>
</div>

{% block js %}
<script>
    document.getElementById("imperial").visibility = "hidden"

    function appear() {
        alert()
        document.getElementById("imperial").visibility = "visible"
    }
</script>
{% endblock %}
{% endblock %}

ethical_eating/templates/users/register.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
   }
   #meter:hover .gauge-c {
        transform:rotate(.5turn);
   }
</style>
{% endblock %}

{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<div id="meter" class="container" style="margin-top: 110px;">
  <div class="gauge-a"></div>
  <div class="gauge-b"></div>
  <div class="gauge-c"></div>
  <div class="gauge-data">
    <h5 style="margin-top: 50px;" id="percent">hover for<br> your ethical level</h5>
  </div>
</div>
<center>
    <h1 class="nice-font title">Register</h1>
    <div class="card space" style="width: 25rem; margin-bottom: 60px;">
      <img src="{% static 'users/kosher_vegan.png' %}" class="card-img-top" style="width: 50%; margin: auto; margin-top: 30px;" alt="...">
      <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary" >Register</button>
          </form>
      </div>
    </div>
</center>
{% endblock %}

ethical_eating/templates/users/trump.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-image: url("{% static 'users/trump.jpeg' %}");
        background-color: #000000;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
   }
</style>
{% endblock %}