ethical_eating/ethical_eating/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('users/', include('users.urls')),
    path('', include('resources.urls')),
]

ethical_eating/forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path('forum/', views.forum, name='forum'),
    path('forum/all/', views.forum_all, name='all'),
    path('forum/get_comment/<int:pk>', views.get_comment, name='get_comment'),
]

ethical_eating/resources/urls.py
from django.urls import path

from resources import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'resources'

urlpatterns = [
    path('', views.index, name='index'),
    path('why', views.why, name='why'),
    path('questions/', views.questions, name='questions'),
    path('resources/', views.resources, name='resources'),
    path('resources/books/', views.books, name='books'),
    path('resources/food/', views.food, name='food'),
    path('resources/food/reviews/<int:pk>', views.reviews, name='reviews'),
    path('resources/products/', views.products, name='products'),
    path('resources/sources/bible', views.bible, name='bible'),
    path('resources/sources/talmud', views.talmud, name='talmud'),
    path('resources/sources/rabbis', views.rabbis, name='rabbis'),
    path('resources/sources/thinkers', views.thinkers, name='thinkers'),
    path('about/', views.about, name='about'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ethical_eating/templates/resources/about.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
   }
   li {
        list-style-type: none;
   }
   #meter:hover .gauge-c {
        transform:rotate(.125turn);
   }
</style>
{% endblock %}

{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<!--<div id="meter" class="container" style="margin-top: 110px;">-->
<!--  <div class="gauge-a"></div>-->
<!--  <div class="gauge-b"></div>-->
<!--  <div class="gauge-c"></div>-->
<!--  <div class="gauge-data">-->
<!--    <h5 style="margin-top: 50px;" id="percent">hover for<br> your ethical level</h5>-->
<!--  </div>-->
<!--</div>-->
<div class="container" style="font-size: 20px; margin-bottom: 30px;">
    <center><h1 class="nice-font space title">About Jewish Ethical Eating</h1></center>
    <div id="what" class="row space">
        <div class="col-md-4">
            <h2 class="nice-font">What is It</h2>
            <img style="height: 200px; width: 200px;" src="{% static 'resources/question.png' %}" alt="Question mark">
        </div>
        <div class="col-md-8">
            <p>
                Vegetarianism is not traditionally a component of mainstream Judaism. Judaism is instead centered around
                Kosher rituals for the consumption of animal products. There are, however, arguments for the integration
                of vegetarianism into Judaism. Genesis 1:29 states "And God said: Behold, I have given you every herb
                yielding seed which is upon the face of all the earth, and every tree that has seed-yielding fruit—to
                you it shall be for food." Many scholars see the Torah as thereby pointing to vegetarianism as an ideal,
                as Adam and Eve did not partake of the flesh of animals as all humans and animals were originally
                commanded by God to only eat plants. According to some interpretations, God's original plan was for
                mankind to be vegetarian, and God only later gave permission for man to eat meat in a covenant with Noah
                (Genesis 9:1–17) as a temporary concession because of Man's weak nature. This concessionary view of
                meat-consumption is based on the scriptural analysis of several Rishonim.
            </p>
            <p>
                The Torah gives precise details on how animals are to be sacrificed and slaughtered (shechita).
                According to Rabbis Shlomo Ephraim Luntschitz and Abraham Isaac Kook the complexity of these laws were
                intended to discourage the consumption of meat. Kashrut may also be designed to discourage killing
                living beings.
            </p>
            <p>
                Some writers assert that the Jewish prophet Isaiah was a vegetarian, on the basis of passages in the
                Book of Isaiah that extol nonviolence and reverence for life, such as Isaiah 1:11, 11:6-9, 65:25, and
                66:3. Some of these writers refer to "the vegetarian Isaiah", "the notorious vegetarian Isaiah", and
                "Isaiah, the vegetarian prophet". Critics of this view argue that none of the Biblical verses in
                question refer to a human diet: they either condemn certain animal sacrifices, or else prophesize
                that carnivorous animals will become herbivorous at the end of days.
            </p>
            <p>
                According to Daniel 1:8-16, the pious Jewish youths Daniel, Shadrach, Meshach, and Abednego refused
                to eat food or drink wine served in Nebuchadnezzar's palace. At Daniel's request, the four boys were
                subjected to a test; they were fed only vegetables and water for ten days. At the end of the ten days,
                the four boys were in better condition than the other boys who ate the king's food.[13] The youths chose
                to eat this food because the king's food was non-kosher, not because the king's food was non-vegan.
            </p>
            <p>
                A number of ancient Jewish sects, including early Karaite sects, regarded the eating of meat as
                prohibited as long as Zion was in ruins and Israel in exile.
            </p>
            <p>
                A number of medieval scholars of Judaism, such as Joseph Albo and Isaac Arama, regard vegetarianism
                as a moral ideal, not out of a concern for animal welfare per se but out of a concern for the moral
                character of the slaughterer. Rabbeinu Asher ben Meshullam was said to have never tasted meat.
            </p>
        </div>
    </div>
    <div id="why" class="row space">
        <div class="col-md-8">
            <p>
                There are several religious and philosophical arguments used by modern Jewish vegetarians regarding the
                ethics of eating meat. According to some, vegetarianism is consistent with the sacred teachings and
                highest ideals of Judaism, including compassion, health, life, conservation of resources, tzedakah,
                kashrut, peace, and justice. In contrast, the mass production and consumption of meat and other animal
                products contradicts many Jewish values and teachings, gravely harming people, animals, communities, and
                the environment.
            </p>
            <p>
                One mitzvah cited by vegetarians is tza'ar ba'alei hayyim; the injunction not to cause "pain to living
                creatures." The laws of shechita are meant to prevent the suffering of animals. However, factory farming
                and high-speed mechanized kosher slaughterhouses have been criticized for failing to meet the essence of
                shechita. Jonathan Safran Foer narrated the short documentary film If This Is Kosher..., which records
                what he considers abuses within the kosher meat industry.
            </p>
            <p>
                Another mitzvah often cited by Jewish vegetarians is bal tashchit; the law which prohibits waste. They
                suggest that an omnivorous diet is wasteful, since it uses 5 times more grain, 10 times more water, 15
                times more land and 20 times more energy when compared to a vegan diet.
            </p>
            <p>
                Some Jewish vegetarians also stress the commandment to maintain one's health and not harm oneself
                (venishmartem me'od lenafshoteichem), and point to research indicating that following a vegetarian diet
                promotes better health. Jewish vegetarians have also argued for environmental vegetarianism, pointing
                out that global warming, hunger and the depletion of natural resources can be lessened by a global shift
                to a vegetarian or vegan diet.
            </p>
        </div>
        <div class="col-md-4">
            <h2 class="nice-font">Why is it important</h2>
            <img style="height: 200px; width: 200px;" src="{% static 'resources/important.png' %}" alt="Exclamation point">
        </div>
    </div>
    <div id="how" class="row space">
        <div class="col-md-4">
            <h2 class="nice-font">How to get involved</h2>
            <img style="height: 200px; width: 200px;" src="{% static 'resources/tools.png' %}" alt="Tools">
        </div>
        <div class="col-md-8">
            <h5>A number of groups promote Jewish vegetarianism:</h5><br>
            <ul>
                <li>
                    <a href="https://www.jewishveg.org/">Jewish Veg</a> was founded by Jonathan Wolf as Jewish
                    Vegetarians of North America (JVNA) in 1975 to promote Jewish vegetarianism. JVNA changed its name
                    to Jewish Veg in 2015. The organization has been noted for its 2007 film A Sacred Duty and for
                    sponsoring university lecture tours by figures including Ori Shavit.
                </li><br>
                <li><a href="https://www.shamayim.us/">SHAMAYIM</a>: Jewish Animal Advocacy, founded and led by Rabbi
                    Dr. Shmuly Yanklowitz, promotes a vegan diet in the Jewish community through animal welfare
                    activism, kosher veganism, and Jewish spirituality. Prior to 2019, it was known as the Shamayim
                    V'Aretz Institute.
                </li><br>
                <li>
                    The <a href="https://www.jvs.org.uk/">Jewish Vegetarian Society</a> (JVS) was co-founded (briefly as
                    the Jewish Vegetarian and Natural Health Society, before the name was abbreviated) by Vivien and
                    Philip Pick in the 1960s with the aim of promoting a kinder society without killing animals for
                    food. Philip Pick was the first chairman of the organisation, with Maurice Norman Lester the first
                    vice chairman and his wife Carole Lester its first secretary.
                </li><br>
                <li>
                    <a href="http://www.amirim-home.co.il/Amirim/index.asp?DBID=1&LNGID=1">Amirim</a>, an Israeli
                    vegetarian moshav (village), was founded in 1958. The founders of Amirim were motivated to create a
                    vegetarian village because of their love for animals and concern for animal rights, as well as for
                    health reasons. Both religious and non-religious families live at Amirim.
                </li><br>
                <li>
                    The <a href="https://chai-online.org/">"Concern for Helping Animals in Israel (CHAI)"</a> animal
                welfare organization promotes Jewish vegetarianism; CHAI's building project is named the Isaac Bashevis
                Singer Humane Education Center.
                </li><br>
                <li>
                    <a href="https://www.behemla.org.il/">Behemla</a> is a Haredi organization that advocates against
                    animal cruelty and promotes veganism.
                </li><br>
                <li>
                    <a href="https://animals-now.org/en/">Animals</a> is an Israeli animal rights organization that
                    promotes Jewish vegetarianism on their website and has been described as a Jewish vegetarian
                    organization. The group was known as Anonymous for Animal Rights from its founding in 1994 until
                    2018.
                </li><br>
                <li>
                    <a href="https://vegan-friendly.co.il/">Vegan Friendly</a> is an organization in Tel Aviv that works
                    to make veganism mainstream, organizes an annual "Vegan Congress," and promotes the vegan
                    celebration of Jewish holidays.
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

ethical_eating/templates/resources/bible.html
{% extends 'base.html' %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
   }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Bible Sources</h1></center>
<div class="space">
    {% for verse in bible %}
    <p class="bible-font" style="font-size: 40px">{{ verse }}</p>
    {% endfor %}
</div>
{% endblock %}

ethical_eating/templates/resources/books.html
{% extends 'base.html' %}

{% block css %}
<style>
     body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Books</h1></center>
<div class="container space">
    <div class="row">
        {% for book in books %}
        <div class="card" style="width: 11rem; margin-right: 10px; margin-bottom: 10px;">
            <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p class="card-text">{{ book.author }}</p>
                <a href="{{ book.site }}" class="btn btn-primary">Buy</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ethical_eating/templates/resources/food.html
{% extends 'base.html' %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Restaurants</h1></center>
{% for restaurant in restaurants %}
<div class="card text-center space">
    <div class="card-header">
        Featured
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ restaurant.name }}</h5>
        <p class="card-text">Location: {{ restaurant.address }} {{ restaurant.city }} {{ restaurant.country }}</p>
        <a href="{{ restaurant.site }}" class="btn btn-primary">Visit Site</a>
        <a href="{% url 'resources:reviews' restaurant.id %}" class="btn btn-primary">Reviews</a>
    </div>
    <div class="card-footer text-muted">
        {% if restaurant.get_avg %}
        Rating: {{ restaurant.get_avg }}
        {% endif %}
    </div>
</div>
{% endfor %}
{% endblock %}

ethical_eating/templates/resources/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
     body {
        background-image: linear-gradient(rgba(60, 60, 60, 0.6), rgba(60, 60, 60, 0.6)), url("{% static 'resources/carrot_lox.jpg' %}");
        background-color:   #020202;
        background-repeat: no-repeat;
        background-size: auto, 108%;
     }
     .top-buffer {
        margin-top: 35px;
     }
     li {
        list-style-type: none;
        background-color: #34deb387;
        margin-bottom: 5px;
     }
     input[type="radio"] {
        -ms-transform: scale(1.5); /* IE 9 */
        -webkit-transform: scale(1.5); /* Chrome, Safari, Opera */
        transform: scale(1.5);
     }
</style>
{% endblock %}

{% block content %}
<center>
    <img src="{% static 'resources/kosher_vegan.png' %}" class="space" width="350" height="175" alt="symbols">
    <h1 style="font-size: 80px;" class="nice-font text-light">Are You a Jewish Ethical Eater?</h1>
    <a href="#quiz_title" class="btn btn-danger btn-lg space">Take the Quiz</a>
</center>
<div style="margin-top: 590px; margin-left: 90px;">
    <h2 class="nice-font" style="color: lime;">Science-backed, bestial consumption quiz</h2>
    <h5 class="nice-font" style="color: lime;" id="quiz_title">See where you are on the range of jewish dietary ethics</h5>
    <form method="post" class="text-light quiz-font space" style="font-size: 25px;">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="booton" style="margin-bottom: 80px;" type="submit" class="btn btn-outline-secondary">Submit</button>
    </form>
{% endblock %}

ethical_eating/templates/resources/products.html
{% extends 'base.html' %}

{% block css %}
<style>
     body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Products</h1></center>
<div class="container space">
    <div class="row">
        {% for product in products %}
        <div class="card" style="width: 11rem; margin-right: 10px; margin-bottom: 10px;">
            <img src="{{ product.pic.url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ product }}</h5>
                <a href="{{ product.site }}" class="btn btn-primary">Website</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ethical_eating/templates/resources/questions.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-image: linear-gradient(rgba(170, 170, 170, 0.8), rgba(170, 170, 170, 0.8)), url("{% static 'resources/avocado.jpg' %}");
        background-color: #abebc6;
   }
   #meter:hover .gauge-c {
        transform:rotate(.375turn);
     }
</style>
{% endblock %}

{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<!--<div id="meter" class="container" style="margin-top: 110px;">-->
<!--  <div class="gauge-a"></div>-->
<!--  <div class="gauge-b"></div>-->
<!--  <div class="gauge-c"></div>-->
<!--  <div class="gauge-data">-->
<!--    <h5 style="margin-top: 50px;" id="percent">hover for<br> your ethical level</h5>-->
<!--  </div>-->
<!--</div>-->
<center><h1 class="nice-font space ledge title">FAQs</h1></center>
<div class="container space">
    <div class="row">
        <div class="col-md-8">
            {% for query in queries %}
            <ul style="margin-bottom: 50px;" class="list-group">
              <li class="list-group-item active">{{ query.question }}</li>
              <li class="list-group-item">{{ query.answer }}<br>
                  <p style="font-size: 11px;">Find this answer helpful?   <a href="#">yes</a></p>
              </li>
            </ul>
            {% endfor %}
        </div>
        <div class="card-mx-auto col-md-4">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                             <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <button type="submit" class="btn btn-secondary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ethical_eating/templates/resources/rabbis.html
{% extends 'base.html' %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Rabbinic Sources</h1></center>
{% endblock %}

ethical_eating/templates/resources/resources.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
     body {
        background-color: #abebc6;
     }
     h2 {
        margin-left: 50px;
     }
</style>
{% endblock %}


{% block content %}
<div class="alert alert-success quiz-font" style="font-size: 25px;" role="alert">
  {% if messages %}{% for m in messages %}{{ m.message }}{% endfor %}{% endif %}
</div>
<center><h1 class="nice-font space title">Resources</h1></center>

<div class="container space">
    <!--  book section  -->
    <div class="row">
        <div class="col-md-4">
            <h2 class="nice-font">Books</h2>
            <img style="height: 180px; width: 200px;" src="{% static 'resources/Book.png' %}" alt="books"><br>
            <a href="{% url 'resources:books' %}" class="btn btn-secondary space">See All</a>
        </div>
        <div class="col-md-8">
            <div class="row">
                {% for book in books %}
                <div class="card" style="width: 11rem; margin-right: 10px;">
                    <img src="{{ book.cover.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ book.title }}</h5>
                        <p class="card-text">{{ book.author }}</p>
                        <a href="{{ book.site }}" class="btn btn-primary">Buy</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!--  source section  -->
    <div id="sources" class="row space">
        <div class="col-md-8">
            <h4 class="bible-font">And God said: "Behold, I have given you every herb-yielding seed which is upon the face of all the earth,
                and every tree that has seed-yielding fruit - to you it shall be for food."<br>
                    Genesis 1:29
            </h4>
            <div style="margin-top: 40px;" class="row">
                <div class="col-md">
                    <a href="{% url 'resources:bible' %}" class="btn btn-secondary">Bible</a>
                </div>
                <div class="col-md">
                    <a href="{% url 'resources:talmud' %}" class="btn btn-secondary">Talmud</a>
                </div>
                <div class="col-md">
                    <a href="{% url 'resources:rabbis' %}" class="btn btn-secondary">Rabbis</a>
                </div>
                <div class="col-md">
                    <a href="{% url 'resources:thinkers' %}" class="btn btn-secondary">Contemporary thinkers</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h2 class="nice-font">Sources</h2>
            <img style="height: 200px; width: 200px;" src="{% static 'resources/file.png' %}" alt="source">
        </div>
    </div>
    <div class="row space">
        <div class="col-md-4">
            <!--  restaurant section  -->
            <h2 class="nice-font">Restaurants</h2>
            <img style="height: 170px; width: 200px;" src="{% static 'resources/plate.png' %}" alt="place setting">
        </div>
        <div class="col-md-8">
            <div class="card text-center">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    {% for restaurant in restaurants %}
                    <h5 class="card-title">{{ restaurant.name }}</h5>
                    <p class="card-text">Location: {{ restaurant.address }} {{ restaurant.city }} {{ restaurant.country }}</p>
                    <a href="{{ restaurant.site }}" class="btn btn-primary">Visit Site</a>
                    <a href="{% url 'resources:reviews' restaurant.id %}" class="btn btn-primary">Reviews</a>
                </div>
                <div class="card-footer text-muted">
                     {% if restaurant.get_avg %}
                        Rating: {{ restaurant.get_avg }}
                     {% endif %}
                </div>
                {% endfor %}
            </div>
            <a href="{% url 'resources:food' %}" class="btn btn-secondary">See All</a>
        </div>
    </div>
    <!--  product section  -->
    <div class="row space" style="margin-bottom: 90px;">
        <div class="col-md-8">
            <div class="row">
            {% for product in products %}
                <div class="card" style="width: 11rem; margin-right: 10px;">
                    <img src="{{ product.pic.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product }}</h5>
                        <a href="{{ product.site }}" class="btn btn-primary">Website</a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div style="margin-top: 40px;" class="row">
                <div class="col-md">
                    <a href="{% url 'resources:products' %}" class="btn btn-secondary">See All</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <h2 class="nice-font">Products</h2>
            <img style="height: 200px; width: 200px;" src="{% static 'resources/box2.png' %}" alt="box">
        </div>
    </div>
</div>
{% endblock %}

ethical_eating/templates/resources/reviews.html
{% extends 'base.html' %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Restaurants</h1></center>
<div class="container space">
    <div class="row">
        <div class="col-md-8">
            <div class="card text-center space">
                <div class="card-header">
                    Featured
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ restaurant.name }}</h5>
                    <p class="card-text">Location: {{ restaurant.address }} {{ restaurant.city }} {{ restaurant.country }}</p>
                    <a href="{{ restaurant.site }}" class="btn btn-primary">Visit Site</a>
                </div>
                <div class="card-footer text-muted">
                    {% if restaurant.get_avg != None %}
                    Rating: {{ restaurant.get_avg }}
                    {% endif %}
                </div>
            </div>
            <h3 class="space">Reviews</h3>
            {% for review in restaurant.reviews.all %}
            <div class="card text-white bg-info mb-3" style="max-width: 18rem;">
                <div class="card-header">By: {{ review.author }}</div>
                    <div class="card-body">
                    <h5 class="card-title">Rating: {{ review.rate }}</h5>
                    <p class="card-text">{{ review.text }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="card-mx-auto col-md-4">
            <h3>Write a Review:</h3>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if messages %}
                        <ul class="messages">
                            {% for message in messages %}
                             <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <button type="submit" class="btn btn-secondary" >Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ethical_eating/templates/resources/talmud.html
{% extends 'base.html' %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Talmudic Sources</h1></center>
{% endblock %}

ethical_eating/templates/resources/thinkers.html
{% extends 'base.html' %}

{% block css %}
<style>
   body {
        background-color: #abebc6;
     }
</style>
{% endblock %}

{% block content %}
<center><h1 class="nice-font space title">Contemporary Thinkers</h1></center>
{% endblock %}

ethical_eating/templates/resources/why.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
<style>
   body {
        background-image: url("{% static 'resources/institution.jpg' %}");
        background-color: #000000;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-position: center;
        background-size: 90%;
   }
</style>
{% endblock %}